### ISSUE TITLE
Multiplayer Explained crashing on Alpha 10

### ISSUE THREAD

**Issue by danhealy** [MitchMakesThings/Godot-Things#3]
Loading the server, then the client, causes both instances to crash for me using 4.0a10, Windows 10

Is it working for you? a10 or a11?

**Comment by Linko-3D** [comment]
Hello, it is normal, it is for 3.x only. I will make a version for Godot 4.x.

**Comment by MitchMakesThings** [comment]
@danhealy Sorry, I was expecting this to break with alpha 10 but I forgot to check. There's a reasonable chance it'll continue to break with new alpha releases.

The issue was that upgrading to the new alpha makes the scenes forget what their replicated variables are. The fix is to use the editor to set the synced variables again (or tweak the .tscn file if you're feeling brave)

Thanks for reporting the issue :)

**Comment by MitchMakesThings** [comment]
> Hello, it is normal, it is for 3.x only. I will make a version for Godot 4.x.

@Linko-3D I think you've got a different project in mind. These networking examples are Godot 4 specific, they're demoing the new networking nodes that were added as part of 4.0
